site_name: Fichas estudio
theme:
#  readthedocs
 material
# nav:
#     - temario-a1.md

plugins:
    - tags
    - macros

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    #- def_list
    - pymdownx.tasklist:
          custom_checkbox: false